### ISSUE TITLE
Máscara de Hora

### ISSUE THREAD

**Issue by aquintiliano** [jansenfelipe/androidmask#3]
Opa, tudo beleza?
Estou usando sua lib, mas to com problema com o formato ##:##
Ele começa a colocar mais ":" depois de três digitos, não sei pq

Outra coisa, poderia excluir do projeto o ic_launcher.png? As vezes dá problemas e por ser uma lib, vc não deve estar usando isso pra nada, certo? 

Obrigado

**Comment by appersiano** [comment]
Hi, I had the same issue (##:##) and I solved this "problem" with a commit to the main project. Try the latest version available! 

For the second problem there is another Issue where I answered,  (https://github.com/jansenfelipe/androidmask/issues/4)

**Comment by jansenfelipe** [comment]
Version 1.0.1 published 4f317679b32
