### ISSUE TITLE
Remove "android:icon" from manifest

### ISSUE THREAD

**Issue by wviana** [jansenfelipe/androidmask#4]
When importing it conflicts with my application icon property.
As it's a library I think it's no necessary to have an icon property in the manifest file.

To solve the problem when building right now, I'm removing the icon property from my app manifest.

PS: Thank you for the awesome library. I saw the code, later I'll fork and send some improvements.

**Comment by appersiano** [comment]
It is not necessary to remove your icon, just use into your manifest the attribute `tools:replace="android:icon"`

**Comment by jansenfelipe** [comment]
Version 1.0.1 published 4f317679b32
