### ISSUE TITLE
AndroidManifest.xml label attribute

### ISSUE THREAD

**Issue by jlccaires** [jansenfelipe/androidmask#7]
Please, remove the android:label attribute.
Error:
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@label value=(@string/app_name) from AndroidManifest.xml:12:9-41
>     is also present at [br.com.jansenfelipe:androidmask:1.0.1] AndroidManifest.xml:11:9-36 value=(AndroidMask)
>     Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5-34:19 to override

**Comment by saviocmc** [comment]
+1

**Comment by mvnthomaz** [comment]
I recompiled the library 'com.github.maarqin:androidmask:2.0.0'

**Comment by jlccaires** [comment]
Update README.md too

**Comment by juniorlazzarini** [comment]
Just open manifest.xml and add tools:replace="android:label" to application label.

**Comment by jlccaires** [comment]
![image](https://user-images.githubusercontent.com/842600/27842120-5d814b9a-60dd-11e7-97a8-fa52bd0077e6.png)
