### ISSUE TITLE
Como usar no TextView?

### ISSUE THREAD

**Issue by b-runo** [jansenfelipe/androidmask#9]
Tentei usar no TextView:

MaskEditTextChangedListener maskCpf = new MaskEditTextChangedListener("##,##",meuTextView);

E diz que tem que só pode ser um editText, tem como usar no TextView?

**Comment by j3frsn** [comment]
Pelo que vi no código fonte da classe `MaskEditTextChangedListener`, somente `TextView`'s e filhas são aceitas, @b-runo. Salvo alguma outra limitação que eu desconheça, dá pra usar esta lib numa `TextView` se o @jansenfelipe deixar o código mais genérico. E dá pra fazer isto exigindo ou a própria `TextView,` da qual `EditText` é filha, ou, pra deixar a lib ainda mais genérica e abrangente, exigindo uma `View`.

Atualização: Numa (ultra)rápida tentativa que acabo de fazer para tentar resolver o problema em questão, percebi que nem `TextView` nem `View` possui alguns atributos e métodos usados pela lib, justificando o motivo do @jansenfelipe não tê-la deixado mais mais genérica.

**Comment by b-runo** [comment]
Que pena seria uma boa, mas obrigado.
